<?php

declare(strict_types=1);

namespace Solo\BaseRepository;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Query\QueryBuilder;
use Solo\BaseRepository\Internal\AdvisoryLock;
use Solo\BaseRepository\Internal\CriteriaBuilder;
use Solo\BaseRepository\Internal\EagerLoadingService;
use Solo\BaseRepository\Internal\Identifier;
use Solo\BaseRepository\Internal\ModelMapper;
use Solo\BaseRepository\Internal\PivotService;
use Solo\BaseRepository\Internal\QueryFactory;
use Solo\BaseRepository\Internal\SoftDeleteService;
use Solo\BaseRepository\Internal\TranslationService;
use Solo\BaseRepository\Relation\AbstractRelation;
use Solo\BaseRepository\Relation\BelongsTo;
use Solo\BaseRepository\Relation\BelongsToMany;
use Solo\BaseRepository\Relation\HasMany;
use Solo\BaseRepository\Relation\HasOne;
use Solo\BaseRepository\Relation\RelationKind;
use Solo\BaseRepository\Relation\RelationType;

/**
 * @template TModel of object
 * @implements RepositoryInterface<TModel>
 *
 * @phpstan-import-type RelationMeta from CriteriaBuilder
 */
abstract class BaseRepository implements RepositoryInterface
{
    protected string $primaryKey = 'id';

    /**
     * Whether the table's primary key is generated by the database
     * (AUTO_INCREMENT / SERIAL / IDENTITY).
     *
     * When false, create() requires the PK to be present in $data and will
     * not fall back to Connection::lastInsertId().
     */
    protected bool $autoIncrement = true;

    protected CriteriaBuilder $criteriaBuilder;
    protected ModelMapper $modelMapper;
    protected QueryFactory $queryFactory;

    protected ?SoftDeleteService $softDeleteService = null;
    protected ?EagerLoadingService $eagerLoadingService = null;
    protected ?TranslationService $translationService = null;
    private ?PivotService $pivotService = null;
    private ?AdvisoryLock $advisoryLock = null;

    /** Active locale for the next query. */
    private ?string $currentLocale = null;

    /** Optional fallback locale: fields empty in the active locale fall back to it. */
    private ?string $fallbackLocale = null;

    /** @var array<string, RelationMeta>|null Memoized — invalidated only on relationConfig mutation, which we don't support. */
    private ?array $compiledRelationsCache = null;

    /** @var array<string, callable(mixed): (array<string|int, mixed>|null)>|null Memoized, validated scopes(). */
    private ?array $scopesCache = null;

    protected ?string $deletedAtColumn = null;
    /** @var array<string, RelationType|mixed> */
    protected array $relationConfig = [];

    /**
     * Translation table config - override in child classes.
     * Set to enable automatic LEFT JOIN with translation table when locale is set.
     *
     * Example:
     *   protected ?array $translationConfig = [
     *       'table' => 'product_translations',
     *       'foreignKey' => 'product_id',
     *       'fields' => ['name', 'description', 'h1', 'meta_title', 'meta_description'],
     *   ];
     *
     * @var array{table: string, foreignKey: string, fields: list<string>}|null
     */
    protected ?array $translationConfig = null;

    /**
     * @param Connection $connection
     * @param class-string<TModel> $modelClass
     * @param non-empty-string $table
     * @param non-empty-string|null $tableAlias
     * @param non-empty-string $mapperMethod
     */
    /** @var non-empty-string Resolved once from $tableAlias ?: substr($table, 0, 1). */
    private string $resolvedAlias;

    public function __construct(
        protected Connection $connection,
        /** @var class-string<TModel> */
        protected string $modelClass,
        protected string $table,
        protected ?string $tableAlias = null,
        protected string $mapperMethod = 'fromArray'
    ) {
        /** @var non-empty-string $alias */
        $alias = $tableAlias !== null && $tableAlias !== '' ? $tableAlias : substr($this->table, 0, 1);
        $this->resolvedAlias = $alias;

        $this->criteriaBuilder = new CriteriaBuilder();
        $this->modelMapper = new ModelMapper($this->modelClass, $this->mapperMethod);
        $this->queryFactory = new QueryFactory($this->connection, $this->table, $this->resolvedAlias);
        $this->initializeServices();
    }

    private function initializeServices(): void
    {
        if ($this->deletedAtColumn !== null) {
            $this->softDeleteService = new SoftDeleteService($this->deletedAtColumn);
        }

        if ($this->translationConfig !== null) {
            $this->translationService = new TranslationService(
                $this->translationConfig['table'],
                $this->translationConfig['foreignKey'],
                $this->translationConfig['fields'],
            );
        }
    }

    private function getEagerLoadingService(): EagerLoadingService
    {
        return $this->eagerLoadingService ??= new EagerLoadingService();
    }

    protected function queryBuilder(): QueryBuilder
    {
        return $this->queryFactory->builder();
    }

    protected function table(): QueryBuilder
    {
        $qb = $this->queryFactory->tableSelectAll();

        if ($this->translationService !== null && $this->currentLocale !== null) {
            $this->translationService->applyJoin(
                $qb,
                $this->getTableAlias(),
                $this->primaryKey,
                $this->currentLocale,
                $this->fallbackLocale,
            );
        }

        return $qb;
    }

    /**
     * Set locale for translation JOIN.
     * When set, the next query will LEFT JOIN the translation table and include translated fields.
     *
     * Pass $fallbackLocale to COALESCE fields that are empty/missing in $locale onto
     * the fallback locale (e.g. show the default-language value until translated).
     *
     * Usage: $repo->withLocale('uk')->findBy($criteria)
     *        $repo->withLocale('ru', 'uk')->findBy($criteria)
     */
    public function withLocale(string $locale, ?string $fallbackLocale = null): static
    {
        $this->currentLocale = $locale;
        $this->fallbackLocale = $fallbackLocale;
        return $this;
    }

    /**
     * Clear locale (disable translation JOIN)
     */
    public function withoutLocale(): static
    {
        $this->currentLocale = null;
        $this->fallbackLocale = null;
        return $this;
    }

    /**
     * Run $fn and clear currentLocale afterwards so withLocale() never leaks
     * across calls.
     *
     * @template T
     * @param \Closure(): T $fn
     * @return T
     */
    private function withLocaleScope(\Closure $fn): mixed
    {
        try {
            return $fn();
        } finally {
            $this->currentLocale = null;
            $this->fallbackLocale = null;
        }
    }

    /**
     * @return non-empty-string
     */
    private function getTableAlias(): string
    {
        return $this->resolvedAlias;
    }

    /**
     * @return non-empty-string
     */
    public function getTableName(): string
    {
        return $this->table;
    }

    /**
     * @return non-empty-string
     */
    public function getPrimaryKeyName(): string
    {
        return $this->primaryKey;
    }

    public function getConnection(): Connection
    {
        return $this->connection;
    }

    /**
     * @return array{table: string, foreignKey: string, fields: list<string>}|null
     */
    public function getTranslationConfig(): ?array
    {
        return $this->translationConfig;
    }

    /**
     * Seed a translation row for each of $locales using $values, skipping locales
     * that already have one. Intended for entity creation: every active locale
     * starts from the operator's initial text (typically the default-language
     * value) and can be translated later, so reads never hit a missing
     * translation. Only keys present in translationConfig['fields'] are written;
     * a no-op when there is no translationConfig or $locales is empty.
     *
     * An existing (foreignKey, locale) row is left untouched — skipping uses the
     * platform's insert-or-ignore form (MySQL INSERT IGNORE, SQLite INSERT OR
     * IGNORE, otherwise ON CONFLICT DO NOTHING), so the translation table must
     * have a UNIQUE(foreignKey, locale) constraint. For single-locale edits write
     * the translation row directly (e.g. updateBy on the translation repository).
     *
     * @param list<string> $locales
     * @param array<string, scalar|null> $values
     * @return int Rows actually inserted (locales that already existed are skipped)
     */
    public function seedTranslations(int|string $id, array $locales, array $values): int
    {
        if ($this->translationConfig === null || $locales === []) {
            return 0;
        }

        $cols = array_values(array_filter(
            $this->translationConfig['fields'],
            static fn(string $field): bool => array_key_exists($field, $values)
        ));
        if ($cols === []) {
            return 0;
        }

        // Identifiers come from $translationConfig, validated in TranslationService.
        $columnList = implode(', ', $cols);
        $rowPlaceholder = '(' . implode(', ', array_fill(0, count($cols) + 2, '?')) . ')';

        $params = [];
        foreach ($locales as $locale) {
            $params[] = $id;
            $params[] = $locale;
            foreach ($cols as $c) {
                $params[] = $values[$c];
            }
        }

        $platform = $this->connection->getDatabasePlatform();
        if ($platform instanceof AbstractMySQLPlatform) {
            $verb = 'INSERT IGNORE INTO';
            $onConflict = '';
        } elseif ($platform instanceof SQLitePlatform) {
            $verb = 'INSERT OR IGNORE INTO';
            $onConflict = '';
        } else {
            $verb = 'INSERT INTO';
            $onConflict = ' ON CONFLICT DO NOTHING';
        }

        $sql = sprintf(
            '%s %s (%s, locale, %s) VALUES %s%s',
            $verb,
            $this->translationConfig['table'],
            $this->translationConfig['foreignKey'],
            $columnList,
            implode(', ', array_fill(0, count($locales), $rowPlaceholder)),
            $onConflict,
        );

        return (int) $this->connection->executeStatement($sql, $params);
    }

    /**
     * @return TModel|null
     */
    public function find(int|string $id): ?object
    {
        return $this->findOneBy([$this->primaryKey => $id]);
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, 'ASC'|'DESC'>|null $orderBy
     * @return TModel|null
     */
    public function findOneBy(array $criteria, ?array $orderBy = null): ?object
    {
        return $this->withLocaleScope(function () use ($criteria, $orderBy): ?object {
            $criteria = $this->prepareCriteria($criteria);

            $qb = $this->applyCriteria($this->table(), $criteria);
            if ($orderBy) {
                $this->applyOrderBy($qb, $orderBy);
            }
            $row = $qb->executeQuery()->fetchAssociative();

            if (!$row) {
                // with() is one-shot per query; consume it even when nothing matched.
                $this->eagerLoadingService?->reset();
                return null;
            }

            $item = $this->mapRowToModel($row);

            if ($this->eagerLoadingService && $this->eagerLoadingService->hasRelations()) {
                try {
                    $items = $this->eagerLoadingService->loadRelations([$item], [$this, 'loadEagerRelations']);
                } finally {
                    $this->eagerLoadingService->reset();
                }
                return $items[0] ?? null;
            }

            return $item;
        });
    }

    /**
     * @return list<TModel>
     */
    public function findAll(): array
    {
        return $this->findBy([]);
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, 'ASC'|'DESC'>|null $orderBy
     * @return list<TModel>
     */
    public function findBy(array $criteria, ?array $orderBy = null, ?int $perPage = null, ?int $page = null): array
    {
        return $this->withLocaleScope(function () use ($criteria, $orderBy, $perPage, $page): array {
            $criteria = $this->prepareCriteria($criteria);

            $qb = $this->applyCriteria($this->table(), $criteria);
            if ($orderBy) {
                $this->applyOrderBy($qb, $orderBy);
            }
            if ($perPage !== null) {
                $offset = (($page ?? 1) - 1) * $perPage;
                $qb->setFirstResult($offset)->setMaxResults($perPage);
            }
            $rows = $qb->executeQuery()->fetchAllAssociative();
            $items = array_map(fn(array $r) => $this->mapRowToModel($r), $rows);

            if ($this->eagerLoadingService && $this->eagerLoadingService->hasRelations()) {
                try {
                    $items = $this->eagerLoadingService->loadRelations($items, [$this, 'loadEagerRelations']);
                } finally {
                    $this->eagerLoadingService->reset();
                }
            }

            return $items;
        });
    }

    /**
     * @param array<string, mixed> $data
     */
    public function insert(array $data): int
    {
        $qb = $this->queryFactory->insertBuilder();
        $this->bindInsertValues($qb, $data);
        return $qb->executeStatement();
    }

    /**
     * Bulk-insert records in chunks of 500, batching by column-set.
     *
     * No implicit transaction — matches insert()/update() semantics. Callers that
     * need all-or-nothing should wrap in withTransaction() themselves.
     *
     * @param list<array<string, mixed>> $records
     */
    public function insertMany(array $records): int
    {
        if ($records === []) {
            return 0;
        }

        $affected = 0;
        foreach (array_chunk($records, 500) as $chunk) {
            $groups = [];
            foreach ($chunk as $row) {
                $cols = array_keys($row);
                $sig = implode("\0", $cols);
                if (!isset($groups[$sig])) {
                    $groups[$sig] = ['cols' => $cols, 'rows' => []];
                }
                $groups[$sig]['rows'][] = $row;
            }
            foreach ($groups as $group) {
                $affected += $this->insertBulk($group['cols'], $group['rows']);
            }
        }
        return $affected;
    }

    /**
     * @param array<string, mixed> $data
     * @return TModel
     */
    public function create(array $data): object
    {
        $pkProvided = array_key_exists($this->primaryKey, $data);

        if (!$this->autoIncrement && !$pkProvided) {
            throw new \InvalidArgumentException(sprintf(
                '%s::create(): primary key "%s" must be provided in $data when $autoIncrement = false.',
                static::class,
                $this->primaryKey,
            ));
        }

        $qb = $this->queryFactory->insertBuilder();
        $this->bindInsertValues($qb, $data);
        $qb->executeStatement();

        $id = $pkProvided ? $data[$this->primaryKey] : $this->connection->lastInsertId();

        /** @var TModel */
        return $this->find($id) ?? throw new \RuntimeException(sprintf(
            '%s::create(): row not found after insert by primary key %s. '
            . 'If %s has no AUTO_INCREMENT/SERIAL PK, set $autoIncrement = false and pass the PK in $data.',
            static::class,
            var_export($id, true),
            $this->table,
        ));
    }

    /**
     * @param array<string, mixed> $data
     */
    private function bindInsertValues(QueryBuilder $qb, array $data): void
    {
        foreach ($data as $column => $value) {
            $qb->setValue($column, ':' . $column)
                ->setParameter($column, $value);
        }
    }

    /**
     * UPDATE-side analogue of bindInsertValues(). The prefix avoids parameter
     * collisions when the same QB also binds criteria parameters.
     *
     * @param array<string, mixed> $data
     */
    private function bindSetValues(QueryBuilder $qb, array $data, string $paramPrefix = ''): void
    {
        foreach ($data as $column => $value) {
            $param = $paramPrefix . $column;
            $qb->set($column, ':' . $param)
                ->setParameter($param, $value);
        }
    }

    /**
     * @param list<string>                     $columns
     * @param list<array<string, mixed>>       $rows
     */
    private function insertBulk(array $columns, array $rows): int
    {
        foreach ($columns as $col) {
            Identifier::assertSafe($col);
        }
        $placeholderRow = '(' . implode(', ', array_fill(0, count($columns), '?')) . ')';
        $placeholders = implode(', ', array_fill(0, count($rows), $placeholderRow));
        $sql = sprintf(
            'INSERT INTO %s (%s) VALUES %s',
            $this->table,
            implode(', ', $columns),
            $placeholders
        );

        $params = [];
        foreach ($rows as $row) {
            foreach ($columns as $col) {
                $params[] = $row[$col];
            }
        }

        return (int) $this->connection->executeStatement($sql, $params);
    }

    /**
     * @param array<string, mixed> $data
     */
    public function update(int|string $id, array $data): object
    {
        Identifier::assertSafe($this->primaryKey);

        $qb = $this->queryFactory->updateByIdBuilder($this->primaryKey, $id);
        $this->bindSetValues($qb, $data, 'update_');
        $qb->executeStatement();

        $model = $this->find($id);

        if ($model === null) {
            throw new \RuntimeException('Updated record not found');
        }

        return $model;
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, mixed> $data
     */
    public function updateBy(array $criteria, array $data): int
    {
        return $this->withLocaleScope(function () use ($criteria, $data): int {
            $criteria = $this->expandScopesForWrite($criteria);

            $qb = $this->queryFactory->updateBuilder();
            $this->bindSetValues($qb, $data, 'update_');
            $qb = $this->applyCriteria($qb, $criteria, false);
            return (int) $qb->executeStatement();
        });
    }

    public function delete(int|string $id): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy([$this->primaryKey => $id], $this->softDeleteService->getSoftDeleteData());
        }

        return $this->forceDelete($id);
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function deleteBy(array $criteria): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy($criteria, $this->softDeleteService->getSoftDeleteData());
        }

        return $this->forceDeleteBy($criteria);
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function exists(array $criteria): bool
    {
        return $this->withLocaleScope(function () use ($criteria): bool {
            $criteria = $this->prepareCriteria($criteria);

            $qb = $this->applyCriteria($this->table(), $criteria)
                ->select('1')
                ->setMaxResults(1);

            return $qb->executeQuery()->fetchOne() !== false;
        });
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function count(array $criteria): int
    {
        return $this->withLocaleScope(function () use ($criteria): int {
            $criteria = $this->prepareCriteria($criteria);

            $qb = $this->applyCriteria($this->table(), $criteria)
                ->select('COUNT(*)');

            return (int) $qb->executeQuery()->fetchOne();
        });
    }

    public function sum(string $column, array $criteria = []): int|float
    {
        return (float) $this->aggregate('SUM', $column, $criteria);
    }

    public function avg(string $column, array $criteria = []): int|float
    {
        return (float) $this->aggregate('AVG', $column, $criteria);
    }

    public function min(string $column, array $criteria = []): mixed
    {
        return $this->aggregate('MIN', $column, $criteria);
    }

    public function max(string $column, array $criteria = []): mixed
    {
        return $this->aggregate('MAX', $column, $criteria);
    }

    /**
     * @param string $function
     * @param string $column
     * @param array<string|int, mixed> $criteria
     * @return mixed
     */
    protected function aggregate(string $function, string $column, array $criteria): mixed
    {
        return $this->withLocaleScope(function () use ($function, $column, $criteria): mixed {
            $criteria = $this->prepareCriteria($criteria);

            Identifier::assertSafe($column);

            $columnName = $this->getTableAlias() . '.' . $column;

            $qb = $this->queryFactory->builder()
                ->select(sprintf('%s(%s)', $function, $columnName))
                ->from($this->table, $this->getTableAlias());

            $qb = $this->applyCriteria($qb, $criteria);

            return $qb->executeQuery()->fetchOne();
        });
    }

    public function beginTransaction(): void
    {
        $this->connection->beginTransaction();
    }

    public function commit(): void
    {
        $this->connection->commit();
    }

    public function rollBack(): void
    {
        $this->connection->rollBack();
    }

    public function inTransaction(): bool
    {
        return $this->connection->isTransactionActive();
    }

    /**
     * @template TReturn
     * @param callable(RepositoryInterface<TModel>): TReturn $callback
     * @return TReturn
     */
    public function withTransaction(callable $callback): mixed
    {
        return $this->connection->transactional(fn() => $callback($this));
    }

    /**
     * Named criteria scopes — override in child classes.
     *
     * Maps a virtual top-level criteria key to a handler that receives the
     * key's value and returns a criteria fragment (AND-joined with the rest
     * of the criteria) or null/[] to add no condition. The scope key itself
     * never reaches the SQL layer, so externally supplied filters (e.g. HTTP
     * query params) can activate predefined conditions directly:
     *
     *   protected function scopes(): array
     *   {
     *       return [
     *           'scope_key' => fn(mixed $value) => $value === null
     *               ? null                            // no condition added
     *               : ['column' => ['>=' => $value]], // any criteria fragment,
     *                                                 // incl. OR groups and rel.field keys
     *       ];
     *   }
     *
     * Scopes apply to every criteria-accepting method: findBy/findOneBy,
     * count, exists, aggregates, updateBy, deleteBy and forceDeleteBy.
     *
     * Rules — validated once, on first use; violations throw:
     *  - names must be non-empty strings and plain identifiers (no dots, no '!');
     *  - names must not collide with reserved criteria keywords (OR, AND,
     *    LIKE, IN, BETWEEN), the primary key, or the soft-delete column;
     *  - handlers must accept mixed (this file runs under strict_types, so a
     *    narrower parameter type throws TypeError on e.g. HTTP string input)
     *    and return array|null.
     *
     * Caveats:
     *  - scope keys are recognized at the TOP level of the criteria array
     *    only; nested occurrences (inside OR/AND groups, list-form entries,
     *    or other scope fragments) compile as plain columns — never name a
     *    scope after a real column;
     *  - fragments cannot control soft-delete visibility: the '*' sentinel
     *    works only as a top-level criteria value supplied by the caller;
     *  - handlers should be pure; running queries inside a handler is
     *    unsupported.
     *
     * @return array<string, callable(mixed): (array<string|int, mixed>|null)>
     */
    protected function scopes(): array
    {
        return [];
    }

    /**
     * @return array<string, callable(mixed): (array<string|int, mixed>|null)>
     */
    private function compiledScopes(): array
    {
        return $this->scopesCache ??= $this->validateScopes($this->scopes());
    }

    /**
     * Validate the scopes() definition once: names must be plain string
     * identifiers and must not collide with criteria keywords, the primary
     * key, or the soft-delete column — the library generates criteria with
     * those keys itself, and a scope would silently hijack them.
     *
     * @param array<int|string, mixed> $scopes
     * @return array<string, callable(mixed): (array<string|int, mixed>|null)>
     */
    private function validateScopes(array $scopes): array
    {
        /** @var array<string, callable(mixed): (array<string|int, mixed>|null)> $validated */
        $validated = [];

        foreach ($scopes as $name => $handler) {
            if (!is_string($name)) {
                throw new \InvalidArgumentException(
                    'Scope names must be non-empty strings; got key of type ' . get_debug_type($name)
                );
            }

            Identifier::assertSafe($name);

            $upper = strtoupper($name);
            if (
                in_array($upper, CriteriaBuilder::GROUP_KEYS, true)
                || in_array($upper, CriteriaBuilder::WORD_OPERATORS, true)
            ) {
                throw new \InvalidArgumentException(
                    "Scope name '{$name}' collides with a reserved criteria keyword"
                );
            }

            if ($name === $this->primaryKey) {
                throw new \InvalidArgumentException(
                    "Scope name '{$name}' collides with the primary key column"
                );
            }

            if ($name === $this->deletedAtColumn) {
                throw new \InvalidArgumentException(
                    "Scope name '{$name}' collides with the soft-delete column"
                );
            }

            if (!is_callable($handler)) {
                throw new \InvalidArgumentException(
                    "Scope '{$name}' handler must be callable, got " . get_debug_type($handler)
                );
            }

            $validated[$name] = $handler;
        }

        return $validated;
    }

    /**
     * Replace top-level scope keys in $criteria with the fragments their
     * handlers return. Fragments are appended as list-form entries, which
     * CriteriaBuilder compiles as AND-joined groups.
     *
     * Read/write entry points call this via prepareCriteria() and
     * expandScopesForWrite(); custom subclass methods that pass external
     * criteria to applyCriteria() directly should call it themselves.
     *
     * @param array<string|int, mixed> $criteria
     * @return array<string|int, mixed>
     */
    protected function expandScopes(array $criteria): array
    {
        $scopes = $this->compiledScopes();
        if ($scopes === [] || $criteria === []) {
            return $criteria;
        }

        $fragments = [];
        $locale = $this->currentLocale;
        $fallbackLocale = $this->fallbackLocale;

        try {
            foreach ($criteria as $name => $value) {
                if (!is_string($name) || !isset($scopes[$name])) {
                    continue;
                }

                unset($criteria[$name]);

                /** @var mixed $fragment runtime-checked: handlers may violate the docblock contract */
                $fragment = ($scopes[$name])($value);

                if ($fragment === null || $fragment === []) {
                    continue;
                }

                if (!is_array($fragment)) {
                    throw new \InvalidArgumentException(
                        "Scope '{$name}' handler must return array or null, got " . get_debug_type($fragment)
                    );
                }

                $fragments[] = $fragment;
            }
        } finally {
            // Handlers are user code; restore the in-flight locale in case a
            // handler ran a nested query whose locale scope cleared it.
            $this->currentLocale = $locale;
            $this->fallbackLocale = $fallbackLocale;
        }

        // array_merge (not $criteria[] = ...) renumbers integer keys safely
        // even when caller-supplied list-form entries carry arbitrary int keys.
        return $fragments === [] ? $criteria : array_merge($criteria, $fragments);
    }

    /**
     * Criteria pre-processing shared by the read paths: scope expansion runs
     * first, so handlers never see (or consume) the soft-delete key injected
     * afterwards.
     *
     * @param array<string|int, mixed> $criteria
     * @return array<string|int, mixed>
     */
    private function prepareCriteria(array $criteria): array
    {
        $criteria = $this->expandScopes($criteria);

        if ($this->softDeleteService) {
            $criteria = $this->softDeleteService->applyCriteria($criteria);
        }

        return $criteria;
    }

    /**
     * Scope expansion for write paths. Refuses criteria that expansion
     * collapsed to nothing: the caller asked for a filtered write, and
     * issuing it without a WHERE clause would touch every row. An explicitly
     * empty array remains a deliberate full-table write.
     *
     * @param array<string|int, mixed> $criteria
     * @return array<string|int, mixed>
     */
    private function expandScopesForWrite(array $criteria): array
    {
        $expanded = $this->expandScopes($criteria);

        if ($expanded === [] && $criteria !== []) {
            throw new \InvalidArgumentException(
                'Scope expansion removed every criteria condition; refusing an unbounded write. '
                . 'Pass [] explicitly to affect all rows.'
            );
        }

        return $expanded;
    }

    /**
     * Compile $criteria into a WHERE expression and bind its parameters on $qb.
     *
     * Criteria must be pre-processed by the caller: prepareCriteria() on read
     * paths, expandScopesForWrite() on write paths — scope expansion and
     * soft-delete defaults are NOT applied here.
     *
     * @param array<string|int, mixed> $criteria
     */
    protected function applyCriteria(QueryBuilder $qb, array $criteria, bool $useAlias = true): QueryBuilder
    {
        if ($criteria === []) {
            return $qb;
        }

        $expr = $this->criteriaBuilder->build(
            $qb,
            $criteria,
            $useAlias ? $this->getTableAlias() : $this->table,
            $this->primaryKey,
            $this->compileRelationMetadata(),
            $useAlias,
            $this->currentLocale,
        );

        if ($expr !== null) {
            $qb->andWhere($expr);
        }

        return $qb;
    }

    /**
     * @return array<string, RelationMeta>
     */
    private function compileRelationMetadata(): array
    {
        if ($this->compiledRelationsCache !== null) {
            return $this->compiledRelationsCache;
        }

        $result = [];
        foreach ($this->relationConfig as $relation => $config) {
            if (!$config instanceof AbstractRelation) {
                throw new \InvalidArgumentException(
                    "Invalid relation config '{$relation}': expected a Relation instance, got "
                    . get_debug_type($config)
                );
            }

            $repositoryProperty = $config->repository;
            if (!property_exists($this, $repositoryProperty)) {
                throw new \InvalidArgumentException(
                    "Relation '{$relation}' points to missing repository property "
                    . "'\${$repositoryProperty}' on " . static::class
                );
            }

            $relatedRepo = $this->{$repositoryProperty};
            $relatedTable = $relatedRepo->getTableName();
            $relatedPrimaryKey = $relatedRepo->getPrimaryKeyName();

            if ($config instanceof BelongsToMany) {
                $meta = [
                    'kind' => $config->kind,
                    'relatedTable' => $relatedTable,
                    'relatedPrimaryKey' => $relatedPrimaryKey,
                    'pivotTable' => $config->pivot,
                    'foreignPivotKey' => $config->foreignPivotKey,
                    'relatedPivotKey' => $config->relatedPivotKey,
                ];
            } else {
                /** @var BelongsTo|HasMany|HasOne $config */
                $meta = [
                    'kind' => $config->kind,
                    'foreignKey' => $config->foreignKey,
                    'relatedTable' => $relatedTable,
                    'relatedPrimaryKey' => $relatedPrimaryKey,
                ];
            }

            if ($relatedRepo instanceof RepositoryInterface) {
                $translation = $relatedRepo->getTranslationConfig();
                if ($translation !== null) {
                    $meta['translation'] = $translation;
                }
            }

            $result[$relation] = $meta;
        }

        return $this->compiledRelationsCache = $result;
    }

    /**
     * @param array<string, 'ASC'|'DESC'> $orderBy
     */
    protected function applyOrderBy(QueryBuilder $qb, array $orderBy): void
    {
        $this->criteriaBuilder->applyOrderBy($qb, $orderBy, $this->getTableAlias());
    }

    /**
     * @param array<string, mixed> $row
     * @return TModel
     */
    protected function mapRowToModel(array $row): object
    {
        return $this->modelMapper->map($row);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function attach(string $relation, int|string $id, array $relatedIds): void
    {
        $this->getPivotService()->attach($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function detach(string $relation, int|string $id, array $relatedIds = []): void
    {
        $this->getPivotService()->detach($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function sync(string $relation, int|string $id, array $relatedIds): void
    {
        $this->getPivotService()->sync($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    private function resolveBelongsToMany(string $relation): BelongsToMany
    {
        $config = $this->relationConfig[$relation] ?? null;

        if (!$config instanceof BelongsToMany) {
            throw new \InvalidArgumentException(
                "Relation '{$relation}' is not defined or is not a BelongsToMany relation."
            );
        }

        return $config;
    }

    private function getPivotService(): PivotService
    {
        return $this->pivotService ??= new PivotService($this->connection);
    }

    /**
     * Lock row(s) by primary key with SELECT ... FOR UPDATE.
     * Must be called inside a transaction.
     *
     * @param int|string|list<int|string> $id Single ID or list of IDs
     */
    public function lockForUpdate(int|string|array $id): void
    {
        Identifier::assertSafe($this->primaryKey);

        $ids = is_array($id) ? $id : [$id];
        if ($ids === []) {
            return;
        }

        $this->connection->fetchAllAssociative(
            "SELECT {$this->primaryKey} FROM {$this->table}"
            . " WHERE {$this->primaryKey} IN (?) FOR UPDATE",
            [$ids],
            [Identifier::arrayParamTypeFor($ids)]
        );
    }

    /**
     * Run $callback while holding a cross-process advisory lock for this record,
     * releasing it on any outcome (including an exception inside $callback).
     *
     * @template TReturn
     * @param int|string $id Record id the critical section applies to
     * @param callable(RepositoryInterface<TModel>): TReturn $callback
     * @param int $timeout Seconds to wait for the lock before failing
     * @return TReturn
     * @throws LockTimeoutException when the lock cannot be acquired within $timeout
     */
    public function withLock(
        int|string $id,
        callable $callback,
        int $timeout = RepositoryInterface::DEFAULT_LOCK_TIMEOUT
    ): mixed {
        $resource = $this->lockResourceFor($id);
        $lock = $this->advisoryLock ??= new AdvisoryLock($this->connection);

        $lock->acquire($resource, $timeout);
        try {
            return $callback($this);
        } finally {
            $lock->release($resource);
        }
    }

    /**
     * Build the advisory-lock resource name. Includes the database so tenants
     * sharing one server don't collide, the table, and the record id.
     */
    private function lockResourceFor(int|string $id): string
    {
        return ($this->connection->getDatabase() ?? '') . '.' . $this->table . '.' . $id;
    }

    /**
     * Force delete (permanent)
     */
    public function forceDelete(int|string $id): int
    {
        Identifier::assertSafe($this->primaryKey);

        return (int) $this->queryFactory->deleteByIdBuilder($this->primaryKey, $id)
            ->executeStatement();
    }

    /**
     * Force delete by criteria (permanent)
     */
    public function forceDeleteBy(array $criteria): int
    {
        return $this->withLocaleScope(function () use ($criteria): int {
            $criteria = $this->expandScopesForWrite($criteria);

            $qb = $this->queryFactory->deleteBuilder();
            $qb = $this->applyCriteria($qb, $criteria, false);
            return (int) $qb->executeStatement();
        });
    }

    /**
     * Restore soft deleted record
     */
    public function restore(int|string $id): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy([$this->primaryKey => $id], $this->softDeleteService->getRestoreData());
        }
        return 0;
    }

    /**
     * Specify relations to eager load.
     *
     * Throws immediately for filter-only relations (configured without a
     * setter); unknown names keep the tolerant-config contract and are
     * silently ignored at load time.
     */
    public function with(array $relations): static
    {
        if (!empty($this->relationConfig)) {
            $this->assertEagerLoadable($relations);
            $this->getEagerLoadingService()->setRelations($relations);
        }
        return $this;
    }

    /**
     * @param array<int, mixed> $relations
     */
    private function assertEagerLoadable(array $relations): void
    {
        foreach ($relations as $path) {
            if (!is_string($path) || $path === '') {
                continue;
            }

            $top = explode('.', $path, 2)[0];
            $config = $this->relationConfig[$top] ?? null;

            if ($config instanceof AbstractRelation && $config->setter === '') {
                throw new \InvalidArgumentException(
                    "Relation '{$top}' is filter-only (no setter configured) and cannot be eager loaded."
                );
            }
        }
    }

    /**
     * Load eager relations for items
     */
    public function loadEagerRelations(array $items, array $relations): array
    {
        if (empty($this->relationConfig) || empty($items)) {
            return $items;
        }

        $service = $this->getEagerLoadingService();
        $grouped = $service->groupByTopLevel($relations);

        foreach ($grouped as $relation => $nested) {
            $service->loadRelation(
                $items,
                $relation,
                $this->relationConfig,
                $this,
                $nested,
                $this->currentLocale,
                $this->fallbackLocale,
            );
        }

        return $items;
    }
}
