<?php

declare(strict_types=1);

namespace Solo\BaseRepository;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Query\QueryBuilder;
use Solo\BaseRepository\Internal\AdvisoryLock;
use Solo\BaseRepository\Internal\CriteriaBuilder;
use Solo\BaseRepository\Internal\EagerLoadingService;
use Solo\BaseRepository\Internal\Identifier;
use Solo\BaseRepository\Internal\ModelMapper;
use Solo\BaseRepository\Internal\PivotService;
use Solo\BaseRepository\Internal\QueryFactory;
use Solo\BaseRepository\Internal\SoftDeleteService;
use Solo\BaseRepository\Internal\TranslationService;
use Solo\BaseRepository\Relation\AbstractRelation;
use Solo\BaseRepository\Relation\BelongsTo;
use Solo\BaseRepository\Relation\BelongsToMany;
use Solo\BaseRepository\Relation\HasMany;
use Solo\BaseRepository\Relation\HasOne;
use Solo\BaseRepository\Relation\RelationKind;
use Solo\BaseRepository\Relation\RelationType;

/**
 * @template TModel of object
 * @implements RepositoryInterface<TModel>
 *
 * @phpstan-import-type RelationMeta from CriteriaBuilder
 */
abstract class BaseRepository implements RepositoryInterface
{
    protected string $primaryKey = 'id';

    /**
     * Whether the table's primary key is generated by the database
     * (AUTO_INCREMENT / SERIAL / IDENTITY).
     *
     * When false, create() requires the PK to be present in $data and will
     * not fall back to Connection::lastInsertId().
     */
    protected bool $autoIncrement = true;

    protected CriteriaBuilder $criteriaBuilder;
    protected ModelMapper $modelMapper;
    protected QueryFactory $queryFactory;

    protected ?SoftDeleteService $softDeleteService = null;
    protected ?EagerLoadingService $eagerLoadingService = null;
    protected ?TranslationService $translationService = null;
    private ?PivotService $pivotService = null;
    private ?AdvisoryLock $advisoryLock = null;

    /** Active locale for the next query. */
    private ?string $currentLocale = null;

    /** @var array<string, RelationMeta>|null Memoized — invalidated only on relationConfig mutation, which we don't support. */
    private ?array $compiledRelationsCache = null;

    /** @var array<string, true>|null Memoized set of configured relation names, including invalid configs. */
    private ?array $configuredRelationsCache = null;

    protected ?string $deletedAtColumn = null;
    /** @var array<string, RelationType|mixed> */
    protected array $relationConfig = [];

    /**
     * Translation table config - override in child classes.
     * Set to enable automatic LEFT JOIN with translation table when locale is set.
     *
     * Example:
     *   protected ?array $translationConfig = [
     *       'table' => 'product_translations',
     *       'foreignKey' => 'product_id',
     *       'fields' => ['name', 'description', 'h1', 'meta_title', 'meta_description'],
     *   ];
     *
     * @var array{table: string, foreignKey: string, fields: list<string>}|null
     */
    protected ?array $translationConfig = null;

    /**
     * @param Connection $connection
     * @param class-string<TModel> $modelClass
     * @param non-empty-string $table
     * @param non-empty-string|null $tableAlias
     * @param non-empty-string $mapperMethod
     */
    /** @var non-empty-string Resolved once from $tableAlias ?: substr($table, 0, 1). */
    private string $resolvedAlias;

    public function __construct(
        protected Connection $connection,
        /** @var class-string<TModel> */
        protected string $modelClass,
        protected string $table,
        protected ?string $tableAlias = null,
        protected string $mapperMethod = 'fromArray'
    ) {
        /** @var non-empty-string $alias */
        $alias = $tableAlias !== null && $tableAlias !== '' ? $tableAlias : substr($this->table, 0, 1);
        $this->resolvedAlias = $alias;

        $this->criteriaBuilder = new CriteriaBuilder();
        $this->modelMapper = new ModelMapper($this->modelClass, $this->mapperMethod);
        $this->queryFactory = new QueryFactory($this->connection, $this->table, $this->resolvedAlias);
        $this->initializeServices();
    }

    private function initializeServices(): void
    {
        if ($this->deletedAtColumn !== null) {
            $this->softDeleteService = new SoftDeleteService($this->deletedAtColumn);
        }

        if ($this->translationConfig !== null) {
            $this->translationService = new TranslationService(
                $this->translationConfig['table'],
                $this->translationConfig['foreignKey'],
                $this->translationConfig['fields'],
            );
        }
    }

    private function getEagerLoadingService(): EagerLoadingService
    {
        return $this->eagerLoadingService ??= new EagerLoadingService();
    }

    protected function queryBuilder(): QueryBuilder
    {
        return $this->queryFactory->builder();
    }

    protected function table(): QueryBuilder
    {
        $qb = $this->queryFactory->tableSelectAll();

        if ($this->translationService !== null && $this->currentLocale !== null) {
            $this->translationService->applyJoin($qb, $this->getTableAlias(), $this->primaryKey, $this->currentLocale);
        }

        return $qb;
    }

    /**
     * Set locale for translation JOIN.
     * When set, the next query will LEFT JOIN the translation table and include translated fields.
     *
     * Usage: $repo->withLocale('uk')->findBy($criteria)
     */
    public function withLocale(string $locale): static
    {
        $this->currentLocale = $locale;
        return $this;
    }

    /**
     * Clear locale (disable translation JOIN)
     */
    public function withoutLocale(): static
    {
        $this->currentLocale = null;
        return $this;
    }

    /**
     * Run $fn and clear currentLocale afterwards so withLocale() never leaks
     * across calls.
     *
     * @template T
     * @param \Closure(): T $fn
     * @return T
     */
    private function withLocaleScope(\Closure $fn): mixed
    {
        try {
            return $fn();
        } finally {
            $this->currentLocale = null;
        }
    }

    /**
     * @return non-empty-string
     */
    private function getTableAlias(): string
    {
        return $this->resolvedAlias;
    }

    /**
     * @return non-empty-string
     */
    public function getTableName(): string
    {
        return $this->table;
    }

    /**
     * @return non-empty-string
     */
    public function getPrimaryKeyName(): string
    {
        return $this->primaryKey;
    }

    public function getConnection(): Connection
    {
        return $this->connection;
    }

    /**
     * @return array{table: string, foreignKey: string, fields: list<string>}|null
     */
    public function getTranslationConfig(): ?array
    {
        return $this->translationConfig;
    }

    /**
     * @return TModel|null
     */
    public function find(int|string $id): ?object
    {
        return $this->findOneBy([$this->primaryKey => $id]);
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, 'ASC'|'DESC'>|null $orderBy
     * @return TModel|null
     */
    public function findOneBy(array $criteria, ?array $orderBy = null): ?object
    {
        return $this->withLocaleScope(function () use ($criteria, $orderBy): ?object {
            if ($this->softDeleteService) {
                $criteria = $this->softDeleteService->applyCriteria($criteria);
            }

            $qb = $this->applyCriteria($this->table(), $criteria);
            if ($orderBy) {
                $this->applyOrderBy($qb, $orderBy);
            }
            $row = $qb->executeQuery()->fetchAssociative();

            if (!$row) {
                return null;
            }

            $item = $this->mapRowToModel($row);

            if ($this->eagerLoadingService && $this->eagerLoadingService->hasRelations()) {
                $items = $this->eagerLoadingService->loadRelations([$item], [$this, 'loadEagerRelations']);
                $this->eagerLoadingService->reset();
                return $items[0] ?? null;
            }

            return $item;
        });
    }

    /**
     * @return list<TModel>
     */
    public function findAll(): array
    {
        return $this->findBy([]);
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, 'ASC'|'DESC'>|null $orderBy
     * @return list<TModel>
     */
    public function findBy(array $criteria, ?array $orderBy = null, ?int $perPage = null, ?int $page = null): array
    {
        return $this->withLocaleScope(function () use ($criteria, $orderBy, $perPage, $page): array {
            if ($this->softDeleteService) {
                $criteria = $this->softDeleteService->applyCriteria($criteria);
            }

            $qb = $this->applyCriteria($this->table(), $criteria);
            if ($orderBy) {
                $this->applyOrderBy($qb, $orderBy);
            }
            if ($perPage !== null) {
                $offset = (($page ?? 1) - 1) * $perPage;
                $qb->setFirstResult($offset)->setMaxResults($perPage);
            }
            $rows = $qb->executeQuery()->fetchAllAssociative();
            $items = array_map(fn(array $r) => $this->mapRowToModel($r), $rows);

            if ($this->eagerLoadingService && $this->eagerLoadingService->hasRelations()) {
                $items = $this->eagerLoadingService->loadRelations($items, [$this, 'loadEagerRelations']);
                $this->eagerLoadingService->reset();
            }

            return $items;
        });
    }

    /**
     * @param array<string, mixed> $data
     */
    public function insert(array $data): int
    {
        $qb = $this->queryFactory->insertBuilder();
        $this->bindInsertValues($qb, $data);
        return $qb->executeStatement();
    }

    /**
     * Bulk-insert records in chunks of 500, batching by column-set.
     *
     * No implicit transaction — matches insert()/update() semantics. Callers that
     * need all-or-nothing should wrap in withTransaction() themselves.
     *
     * @param list<array<string, mixed>> $records
     */
    public function insertMany(array $records): int
    {
        if ($records === []) {
            return 0;
        }

        $affected = 0;
        foreach (array_chunk($records, 500) as $chunk) {
            $groups = [];
            foreach ($chunk as $row) {
                $cols = array_keys($row);
                $sig = implode("\0", $cols);
                if (!isset($groups[$sig])) {
                    $groups[$sig] = ['cols' => $cols, 'rows' => []];
                }
                $groups[$sig]['rows'][] = $row;
            }
            foreach ($groups as $group) {
                $affected += $this->insertBulk($group['cols'], $group['rows']);
            }
        }
        return $affected;
    }

    /**
     * @param array<string, mixed> $data
     * @return TModel
     */
    public function create(array $data): object
    {
        $pkProvided = array_key_exists($this->primaryKey, $data);

        if (!$this->autoIncrement && !$pkProvided) {
            throw new \InvalidArgumentException(sprintf(
                '%s::create(): primary key "%s" must be provided in $data when $autoIncrement = false.',
                static::class,
                $this->primaryKey,
            ));
        }

        $qb = $this->queryFactory->insertBuilder();
        $this->bindInsertValues($qb, $data);
        $qb->executeStatement();

        $id = $pkProvided ? $data[$this->primaryKey] : $this->connection->lastInsertId();

        /** @var TModel */
        return $this->find($id) ?? throw new \RuntimeException(sprintf(
            '%s::create(): row not found after insert by primary key %s. '
            . 'If %s has no AUTO_INCREMENT/SERIAL PK, set $autoIncrement = false and pass the PK in $data.',
            static::class,
            var_export($id, true),
            $this->table,
        ));
    }

    /**
     * @param array<string, mixed> $data
     */
    private function bindInsertValues(QueryBuilder $qb, array $data): void
    {
        foreach ($data as $column => $value) {
            $qb->setValue($column, ':' . $column)
                ->setParameter($column, $value);
        }
    }

    /**
     * UPDATE-side analogue of bindInsertValues(). The prefix avoids parameter
     * collisions when the same QB also binds criteria parameters.
     *
     * @param array<string, mixed> $data
     */
    private function bindSetValues(QueryBuilder $qb, array $data, string $paramPrefix = ''): void
    {
        foreach ($data as $column => $value) {
            $param = $paramPrefix . $column;
            $qb->set($column, ':' . $param)
                ->setParameter($param, $value);
        }
    }

    /**
     * @param list<string>                     $columns
     * @param list<array<string, mixed>>       $rows
     */
    private function insertBulk(array $columns, array $rows): int
    {
        foreach ($columns as $col) {
            Identifier::assertSafe($col);
        }
        $placeholderRow = '(' . implode(', ', array_fill(0, count($columns), '?')) . ')';
        $placeholders = implode(', ', array_fill(0, count($rows), $placeholderRow));
        $sql = sprintf(
            'INSERT INTO %s (%s) VALUES %s',
            $this->table,
            implode(', ', $columns),
            $placeholders
        );

        $params = [];
        foreach ($rows as $row) {
            foreach ($columns as $col) {
                $params[] = $row[$col];
            }
        }

        return (int) $this->connection->executeStatement($sql, $params);
    }

    /**
     * @param array<string, mixed> $data
     */
    public function update(int|string $id, array $data): object
    {
        Identifier::assertSafe($this->primaryKey);

        $qb = $this->queryFactory->updateByIdBuilder($this->primaryKey, $id);
        $this->bindSetValues($qb, $data, 'update_');
        $qb->executeStatement();

        $model = $this->find($id);

        if ($model === null) {
            throw new \RuntimeException('Updated record not found');
        }

        return $model;
    }

    /**
     * @param array<string|int, mixed> $criteria
     * @param array<string, mixed> $data
     */
    public function updateBy(array $criteria, array $data): int
    {
        return $this->withLocaleScope(function () use ($criteria, $data): int {
            $qb = $this->queryFactory->updateBuilder();
            $this->bindSetValues($qb, $data, 'update_');
            $qb = $this->applyCriteria($qb, $criteria, false);
            return (int) $qb->executeStatement();
        });
    }

    public function delete(int|string $id): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy([$this->primaryKey => $id], $this->softDeleteService->getSoftDeleteData());
        }

        return $this->forceDelete($id);
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function deleteBy(array $criteria): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy($criteria, $this->softDeleteService->getSoftDeleteData());
        }

        return $this->forceDeleteBy($criteria);
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function exists(array $criteria): bool
    {
        return $this->withLocaleScope(function () use ($criteria): bool {
            if ($this->softDeleteService) {
                $criteria = $this->softDeleteService->applyCriteria($criteria);
            }

            $qb = $this->applyCriteria($this->table(), $criteria)
                ->select('1')
                ->setMaxResults(1);

            return $qb->executeQuery()->fetchOne() !== false;
        });
    }

    /**
     * @param array<string|int, mixed> $criteria
     */
    public function count(array $criteria): int
    {
        return $this->withLocaleScope(function () use ($criteria): int {
            if ($this->softDeleteService) {
                $criteria = $this->softDeleteService->applyCriteria($criteria);
            }

            $qb = $this->applyCriteria($this->table(), $criteria)
                ->select('COUNT(*)');

            return (int) $qb->executeQuery()->fetchOne();
        });
    }

    public function sum(string $column, array $criteria = []): int|float
    {
        return (float) $this->aggregate('SUM', $column, $criteria);
    }

    public function avg(string $column, array $criteria = []): int|float
    {
        return (float) $this->aggregate('AVG', $column, $criteria);
    }

    public function min(string $column, array $criteria = []): mixed
    {
        return $this->aggregate('MIN', $column, $criteria);
    }

    public function max(string $column, array $criteria = []): mixed
    {
        return $this->aggregate('MAX', $column, $criteria);
    }

    /**
     * @param string $function
     * @param string $column
     * @param array<string|int, mixed> $criteria
     * @return mixed
     */
    protected function aggregate(string $function, string $column, array $criteria): mixed
    {
        return $this->withLocaleScope(function () use ($function, $column, $criteria): mixed {
            if ($this->softDeleteService) {
                $criteria = $this->softDeleteService->applyCriteria($criteria);
            }

            Identifier::assertSafe($column);

            $columnName = $this->getTableAlias() . '.' . $column;

            $qb = $this->queryFactory->builder()
                ->select(sprintf('%s(%s)', $function, $columnName))
                ->from($this->table, $this->getTableAlias());

            $qb = $this->applyCriteria($qb, $criteria);

            return $qb->executeQuery()->fetchOne();
        });
    }

    public function beginTransaction(): void
    {
        $this->connection->beginTransaction();
    }

    public function commit(): void
    {
        $this->connection->commit();
    }

    public function rollBack(): void
    {
        $this->connection->rollBack();
    }

    public function inTransaction(): bool
    {
        return $this->connection->isTransactionActive();
    }

    /**
     * @template TReturn
     * @param callable(RepositoryInterface<TModel>): TReturn $callback
     * @return TReturn
     */
    public function withTransaction(callable $callback): mixed
    {
        return $this->connection->transactional(fn() => $callback($this));
    }

    /**
     * Compile $criteria into a WHERE expression and bind its parameters on $qb.
     *
     * @param array<string|int, mixed> $criteria
     */
    protected function applyCriteria(QueryBuilder $qb, array $criteria, bool $useAlias = true): QueryBuilder
    {
        if ($criteria === []) {
            return $qb;
        }

        $expr = $this->criteriaBuilder->build(
            $qb,
            $criteria,
            $useAlias ? $this->getTableAlias() : $this->table,
            $this->primaryKey,
            $this->compileRelationMetadata(),
            $this->configuredRelationNames(),
            $useAlias,
            $this->currentLocale,
        );

        if ($expr !== null) {
            $qb->andWhere($expr);
        }

        return $qb;
    }

    /**
     * @return array<string, RelationMeta>
     */
    private function compileRelationMetadata(): array
    {
        if ($this->compiledRelationsCache !== null) {
            return $this->compiledRelationsCache;
        }

        $result = [];
        foreach ($this->relationConfig as $relation => $config) {
            if (!$config instanceof AbstractRelation) {
                continue;
            }

            $repositoryProperty = $config->repository;
            if (!property_exists($this, $repositoryProperty)) {
                continue;
            }

            $relatedRepo = $this->{$repositoryProperty};
            $relatedTable = $relatedRepo->getTableName();
            $relatedPrimaryKey = $relatedRepo->getPrimaryKeyName();

            if ($config instanceof BelongsToMany) {
                $meta = [
                    'kind' => $config->kind,
                    'relatedTable' => $relatedTable,
                    'relatedPrimaryKey' => $relatedPrimaryKey,
                    'pivotTable' => $config->pivot,
                    'foreignPivotKey' => $config->foreignPivotKey,
                    'relatedPivotKey' => $config->relatedPivotKey,
                ];
            } else {
                /** @var BelongsTo|HasMany|HasOne $config */
                $meta = [
                    'kind' => $config->kind,
                    'foreignKey' => $config->foreignKey,
                    'relatedTable' => $relatedTable,
                    'relatedPrimaryKey' => $relatedPrimaryKey,
                ];
            }

            if ($relatedRepo instanceof RepositoryInterface) {
                $translation = $relatedRepo->getTranslationConfig();
                if ($translation !== null) {
                    $meta['translation'] = $translation;
                }
            }

            $result[$relation] = $meta;
        }

        return $this->compiledRelationsCache = $result;
    }

    /**
     * @return array<string, true>
     */
    private function configuredRelationNames(): array
    {
        return $this->configuredRelationsCache ??= array_fill_keys(array_keys($this->relationConfig), true);
    }

    /**
     * @param array<string, 'ASC'|'DESC'> $orderBy
     */
    protected function applyOrderBy(QueryBuilder $qb, array $orderBy): void
    {
        $this->criteriaBuilder->applyOrderBy($qb, $orderBy, $this->getTableAlias());
    }

    /**
     * @param array<string, mixed> $row
     * @return TModel
     */
    protected function mapRowToModel(array $row): object
    {
        return $this->modelMapper->map($row);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function attach(string $relation, int|string $id, array $relatedIds): void
    {
        $this->getPivotService()->attach($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function detach(string $relation, int|string $id, array $relatedIds = []): void
    {
        $this->getPivotService()->detach($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    /**
     * @param list<int|string> $relatedIds
     */
    public function sync(string $relation, int|string $id, array $relatedIds): void
    {
        $this->getPivotService()->sync($this->resolveBelongsToMany($relation), $id, $relatedIds);
    }

    private function resolveBelongsToMany(string $relation): BelongsToMany
    {
        $config = $this->relationConfig[$relation] ?? null;

        if (!$config instanceof BelongsToMany) {
            throw new \InvalidArgumentException(
                "Relation '{$relation}' is not defined or is not a BelongsToMany relation."
            );
        }

        return $config;
    }

    private function getPivotService(): PivotService
    {
        return $this->pivotService ??= new PivotService($this->connection);
    }

    /**
     * Lock row(s) by primary key with SELECT ... FOR UPDATE.
     * Must be called inside a transaction.
     *
     * @param int|string|list<int|string> $id Single ID or list of IDs
     */
    public function lockForUpdate(int|string|array $id): void
    {
        Identifier::assertSafe($this->primaryKey);

        $ids = is_array($id) ? $id : [$id];
        if ($ids === []) {
            return;
        }

        $this->connection->fetchAllAssociative(
            "SELECT {$this->primaryKey} FROM {$this->table}"
            . " WHERE {$this->primaryKey} IN (?) FOR UPDATE",
            [$ids],
            [Identifier::arrayParamTypeFor($ids)]
        );
    }

    /**
     * Run $callback while holding a cross-process advisory lock for this record,
     * releasing it on any outcome (including an exception inside $callback).
     *
     * @template TReturn
     * @param int|string $id Record id the critical section applies to
     * @param callable(RepositoryInterface<TModel>): TReturn $callback
     * @param int $timeout Seconds to wait for the lock before failing
     * @return TReturn
     * @throws LockTimeoutException when the lock cannot be acquired within $timeout
     */
    public function withLock(
        int|string $id,
        callable $callback,
        int $timeout = RepositoryInterface::DEFAULT_LOCK_TIMEOUT
    ): mixed {
        $resource = $this->lockResourceFor($id);
        $lock = $this->advisoryLock ??= new AdvisoryLock($this->connection);

        $lock->acquire($resource, $timeout);
        try {
            return $callback($this);
        } finally {
            $lock->release($resource);
        }
    }

    /**
     * Build the advisory-lock resource name. Includes the database so tenants
     * sharing one server don't collide, the table, and the record id.
     */
    private function lockResourceFor(int|string $id): string
    {
        return ($this->connection->getDatabase() ?? '') . '.' . $this->table . '.' . $id;
    }

    /**
     * Force delete (permanent)
     */
    public function forceDelete(int|string $id): int
    {
        Identifier::assertSafe($this->primaryKey);

        return (int) $this->queryFactory->deleteByIdBuilder($this->primaryKey, $id)
            ->executeStatement();
    }

    /**
     * Force delete by criteria (permanent)
     */
    public function forceDeleteBy(array $criteria): int
    {
        return $this->withLocaleScope(function () use ($criteria): int {
            $qb = $this->queryFactory->deleteBuilder();
            $qb = $this->applyCriteria($qb, $criteria, false);
            return (int) $qb->executeStatement();
        });
    }

    /**
     * Restore soft deleted record
     */
    public function restore(int|string $id): int
    {
        if ($this->softDeleteService) {
            return $this->updateBy([$this->primaryKey => $id], $this->softDeleteService->getRestoreData());
        }
        return 0;
    }

    /**
     * Specify relations to eager load
     */
    public function with(array $relations): static
    {
        if (!empty($this->relationConfig)) {
            $this->getEagerLoadingService()->setRelations($relations);
        }
        return $this;
    }

    /**
     * Load eager relations for items
     */
    public function loadEagerRelations(array $items, array $relations): array
    {
        if (empty($this->relationConfig) || empty($items)) {
            return $items;
        }

        $service = $this->getEagerLoadingService();
        $grouped = $service->groupByTopLevel($relations);

        foreach ($grouped as $relation => $nested) {
            $service->loadRelation($items, $relation, $this->relationConfig, $this, $nested, $this->currentLocale);
        }

        return $items;
    }
}
